// <auto-generated />
using ClassIslandBot;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassIslandBot.Migrations
{
    [DbContext(typeof(BotContext))]
    [Migration("20240920122448_AddIsTracking")]
    partial class AddIsTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ClassIslandBot.Models.Entities.DiscussionAssociation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscussionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTracking")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssueId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DiscussionAssociations");
                });
#pragma warning restore 612, 618
        }
    }
}
