import './globals.d.ts';
/* tslint:disable */
/* eslint-disable */
/**
 * ClassIslandBot - version 1.0
 *
 *
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'DiscussionAssociations.list': ['GET', '/api/v1/discussions'],
  'DiscussionAssociations.create': ['POST', '/api/v1/discussions'],
  'DiscussionAssociations.get': ['GET', '/api/v1/discussions/{id}'],
  'DiscussionAssociations.update': ['PUT', '/api/v1/discussions/{id}'],
  'DiscussionAssociations.delete': ['DELETE', '/api/v1/discussions/{id}'],
  'DiscussionAssociations.MigrateDiscussions': ['GET', '/api/v1/discussions/migrate'],
  'Auth.login': ['GET', '/api/v1/auth/login'],
  'Auth.me': ['GET', '/api/v1/auth/me'],
  'Auth.logout': ['POST', '/api/v1/auth/logout'],
  'GitHubMetadata.getRepositories': ['GET', '/api/v1/github/repositories'],
  'GitHubMetadata.getIssues': ['GET', '/api/v1/github/repositories/{repoId}/issues'],
  'GitHubMetadata.getDiscussions': ['GET', '/api/v1/github/discussions']
};
