/* tslint:disable */
/* eslint-disable */
/**
 * ClassIslandBot - version 1.0
 *
 *
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from './index';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export interface DiscussionAssociationRequest {
  repoId?: string | null;
  discussionId?: string | null;
  issueId?: string | null;
  refCommentId?: string | null;
  isTracking?: boolean;
}
export interface DiscussionAssociationResponse {
  id?: number;
  repoId?: string | null;
  discussionId?: string | null;
  issueId?: string | null;
  refCommentId?: string | null;
  isTracking?: boolean;
}
export interface DiscussionAssociationResponsePaginatedList {
  pageIndex?: number;
  totalPages?: number;
  pageSize?: number;
  itemCount?: number;
  items?: DiscussionAssociationResponse[] | null;
  hasPreviousPage?: boolean;
  hasNextPage?: boolean;
}
export interface GitHubRepositoryOption {
  id?: string | null;
  name?: string | null;
  fullName?: string | null;
  description?: string | null;
  url?: string | null;
}
export interface GitHubDiscussionOption {
  id?: string | null;
  number?: number;
  title?: string | null;
  state?: string | null;
  url?: string | null;
}
export interface GitHubIssueOption {
  id?: string | null;
  number?: number;
  title?: string | null;
  state?: string | null;
  url?: string | null;
}
declare global {
  interface Apis {
    DiscussionAssociations: {
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/discussions
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   pageIndex?: number
       *   pageSize?: number
       *   repoId?: string
       *   discussionId?: string
       *   issueId?: string
       *   isTracking?: boolean
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   pageIndex?: number
       *   totalPages?: number
       *   pageSize?: number
       *   itemCount?: number
       *   // [params1] start
       *   // [items] start
       *   // [items] end
       *   // [params1] end
       *   items?: Array<{
       *     id?: number
       *     repoId?: string | null
       *     discussionId?: string | null
       *     issueId?: string | null
       *     refCommentId?: string | null
       *     isTracking?: boolean
       *   }> | null
       *   hasPreviousPage?: boolean
       *   hasNextPage?: boolean
       * }
       * ```
       */
      list<
        Config extends Alova2MethodConfig<DiscussionAssociationResponsePaginatedList> & {
          params: {
            pageIndex?: number;
            pageSize?: number;
            repoId?: string;
            discussionId?: string;
            issueId?: string;
            isTracking?: boolean;
          };
        }
      >(
        config: Config
      ): Alova2Method<DiscussionAssociationResponsePaginatedList, 'DiscussionAssociations.list', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/v1/discussions
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   repoId?: string | null
       *   discussionId?: string | null
       *   issueId?: string | null
       *   refCommentId?: string | null
       *   isTracking?: boolean
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   id?: number
       *   repoId?: string | null
       *   discussionId?: string | null
       *   issueId?: string | null
       *   refCommentId?: string | null
       *   isTracking?: boolean
       * }
       * ```
       */
      create<
        Config extends Alova2MethodConfig<DiscussionAssociationResponse> & {
          data: DiscussionAssociationRequest;
        }
      >(
        config: Config
      ): Alova2Method<DiscussionAssociationResponse, 'DiscussionAssociations.create', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/discussions/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   id?: number
       *   repoId?: string | null
       *   discussionId?: string | null
       *   issueId?: string | null
       *   refCommentId?: string | null
       *   isTracking?: boolean
       * }
       * ```
       */
      get<
        Config extends Alova2MethodConfig<DiscussionAssociationResponse> & {
          pathParams: {
            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<DiscussionAssociationResponse, 'DiscussionAssociations.get', Config>;
      /**
       * ---
       *
       * [PUT]
       *
       * **path:** /api/v1/discussions/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   repoId?: string | null
       *   discussionId?: string | null
       *   issueId?: string | null
       *   refCommentId?: string | null
       *   isTracking?: boolean
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   id?: number
       *   repoId?: string | null
       *   discussionId?: string | null
       *   issueId?: string | null
       *   refCommentId?: string | null
       *   isTracking?: boolean
       * }
       * ```
       */
      update<
        Config extends Alova2MethodConfig<DiscussionAssociationResponse> & {
          pathParams: {
            id: number;
          };
          data: DiscussionAssociationRequest;
        }
      >(
        config: Config
      ): Alova2Method<DiscussionAssociationResponse, 'DiscussionAssociations.update', Config>;
      /**
       * ---
       *
       * [DELETE]
       *
       * **path:** /api/v1/discussions/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      delete<
        Config extends Alova2MethodConfig<null> & {
          pathParams: {
            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<null, 'DiscussionAssociations.delete', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/discussions/migrate
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      MigrateDiscussions<Config extends Alova2MethodConfig<null>>(
        config?: Config
      ): Alova2Method<null, 'DiscussionAssociations.MigrateDiscussions', Config>;
    };
    GitHubMetadata: {
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/github/repositories
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   keyword?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = Array<{
       *   id?: string | null
       *   name?: string | null
       *   fullName?: string | null
       *   description?: string | null
       *   url?: string | null
       * }>
       * ```
       */
      getRepositories<
        Config extends Alova2MethodConfig<GitHubRepositoryOption[]> & {
          params: {
            keyword?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<GitHubRepositoryOption[], 'GitHubMetadata.getRepositories', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/github/repositories/{repoId}/issues
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   repoId: string
       * }
       * ```
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   keyword?: string
       *   take?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = Array<{
       *   id?: string | null
       *   number?: number
       *   title?: string | null
       *   state?: string | null
       *   url?: string | null
       * }>
       * ```
       */
      getIssues<
        Config extends Alova2MethodConfig<GitHubIssueOption[]> & {
          pathParams: {
            repoId: string;
          };
          params: {
            keyword?: string;
            take?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<GitHubIssueOption[], 'GitHubMetadata.getIssues', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/github/discussions
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   keyword?: string
       *   take?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = Array<{
       *   id?: string | null
       *   number?: number
       *   title?: string | null
       *   state?: string | null
       *   url?: string | null
       * }>
       * ```
       */
      getDiscussions<
        Config extends Alova2MethodConfig<GitHubDiscussionOption[]> & {
          params: {
            keyword?: string;
            take?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<GitHubDiscussionOption[], 'GitHubMetadata.getDiscussions', Config>;
    };
  }

  var Apis: Apis;
}
